// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientsInformationAPI.Data;

#nullable disable

namespace PatientsInformationAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PatientsInformationAPI.Models.Domains.Allergy", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.Domains.Disease", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DiseaseInformation");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.Domains.NCD", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NCD");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.Domains.Patient", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HasEpilepsy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PatientsInforamtion");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.RelationshipModel.Allergies_Details", b =>
                {
                    b.Property<Guid>("AllergiesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AllergiesID", "PatientID");

                    b.HasIndex("PatientID");

                    b.ToTable("Allergies_Details");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.RelationshipModel.Diseases_Details", b =>
                {
                    b.Property<Guid>("DiseaseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiseaseID", "PatientID");

                    b.HasIndex("PatientID");

                    b.ToTable("Diseases_Details");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.RelationshipModel.NCD_Details", b =>
                {
                    b.Property<Guid>("NCDID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NCDID", "PatientID");

                    b.HasIndex("PatientID");

                    b.ToTable("NCD_Details");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.RelationshipModel.Allergies_Details", b =>
                {
                    b.HasOne("PatientsInformationAPI.Models.Domains.Patient", "Patient")
                        .WithMany("Allergies")
                        .HasForeignKey("AllergiesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientsInformationAPI.Models.Domains.Allergy", "Allergy")
                        .WithMany("Patients")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.RelationshipModel.Diseases_Details", b =>
                {
                    b.HasOne("PatientsInformationAPI.Models.Domains.Patient", "Patient")
                        .WithMany("Diseases")
                        .HasForeignKey("DiseaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientsInformationAPI.Models.Domains.Disease", "Disease")
                        .WithMany("Patients")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.RelationshipModel.NCD_Details", b =>
                {
                    b.HasOne("PatientsInformationAPI.Models.Domains.Patient", "Patient")
                        .WithMany("NCDs")
                        .HasForeignKey("NCDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientsInformationAPI.Models.Domains.NCD", "NCD")
                        .WithMany("Patients")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NCD");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.Domains.Allergy", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.Domains.Disease", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.Domains.NCD", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PatientsInformationAPI.Models.Domains.Patient", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Diseases");

                    b.Navigation("NCDs");
                });
#pragma warning restore 612, 618
        }
    }
}
